# Alacritty colors configuration - Dark Blue-Grey background

[colors.primary]
background = '#232321'   # black
foreground = '#D9D8D4'   # light gray text

[colors.cursor]
text = '#1B2428'         # background color for cursor text
cursor = '#D9D8D4'       # cursor color (light gray)

[colors.search]
matches = { foreground = '#D9D8D4', background = '#B1A084' }       # white on tan
focused_match = { foreground = '#D9D8D4', background = '#595643' } # white on dark tan

[colors.normal]
black   = '#232321'  # black (dark blue-grey)
red     = '#B64B1E'  # orange
green   = '#505944'  # green
yellow  = '#B1A084'  # tan
blue    = '#7C8D90'  # blue-gray
magenta = '#9E8882'  # dusty mauve
cyan    = '#7A9B91'  # muted sage
white   = '#D9D8D4'  # light gray

[colors.bright]
black   = '#232321'  # black (dark blue-grey)
red     = '#B64B1E'  # orange
green   = '#505944'  # green
yellow  = '#B1A084'  # tan
blue    = '#7C8D90'  # blue-gray
magenta = '#9E8882'  # dusty mauve
cyan    = '#7A9B91'  # muted sage
white   = '#D9D8D4'  # light gray
