# Default colors
[colors.primary]
background = '#CCCCCC'
foreground = '#474747'

[colors.cursor]
text = '#CCCCCC'
cursor = '#474747'

[colors.search]
matches = { foreground = '#474747', background = '#DEBB64' }
focused_match = { foreground = '#474747', background = '#8DA101' }

# Normal colors
[colors.normal]
black   = '#333333'
red     = '#F85552'
green   = '#8DA101'
yellow  = '#DFA000'
blue    = '#3A94C5'
magenta = '#DF69BA'
cyan    = '#35A77C'
white   = '#C2C2C2'

# Bright colors
[colors.bright]
black   = '#333333'
red     = '#F85552'
green   = '#8DA101'
yellow  = '#DFA000'
blue    = '#3A94C5'
magenta = '#DF69BA'
cyan    = '#35A77C'
white   = '#C2C2C2'
